/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AiAgentIndexRouteImport } from './routes/ai-agent/index'
import { Route as AiAgentSignupRouteImport } from './routes/ai-agent/signup'
import { Route as AiAgentThankYouRouteImport } from './routes/ai-agent/thank-you'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentIndexRoute = AiAgentIndexRouteImport.update({
  id: '/ai-agent/',
  path: '/ai-agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentSignupRoute = AiAgentSignupRouteImport.update({
  id: '/ai-agent/signup',
  path: '/ai-agent/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentThankYouRoute = AiAgentThankYouRouteImport.update({
  id: '/ai-agent/thank-you',
  path: '/ai-agent/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai-agent/signup': typeof AiAgentSignupRoute
  '/ai-agent/thank-you': typeof AiAgentThankYouRoute
  '/ai-agent/': typeof AiAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai-agent/signup': typeof AiAgentSignupRoute
  '/ai-agent/thank-you': typeof AiAgentThankYouRoute
  '/ai-agent': typeof AiAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/ai-agent/signup': typeof AiAgentSignupRoute
  '/ai-agent/thank-you': typeof AiAgentThankYouRoute
  '/ai-agent/': typeof AiAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/ai-agent/signup'
    | '/ai-agent/thank-you'
    | '/ai-agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/ai-agent/signup'
    | '/ai-agent/thank-you'
    | '/ai-agent'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/ai-agent/signup'
    | '/ai-agent/thank-you'
    | '/ai-agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AiAgentSignupRoute: typeof AiAgentSignupRoute
  AiAgentThankYouRoute: typeof AiAgentThankYouRoute
  AiAgentIndexRoute: typeof AiAgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent/': {
      id: '/ai-agent/'
      path: '/ai-agent'
      fullPath: '/ai-agent/'
      preLoaderRoute: typeof AiAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent/signup': {
      id: '/ai-agent/signup'
      path: '/ai-agent/signup'
      fullPath: '/ai-agent/signup'
      preLoaderRoute: typeof AiAgentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent/thank-you': {
      id: '/ai-agent/thank-you'
      path: '/ai-agent/thank-you'
      fullPath: '/ai-agent/thank-you'
      preLoaderRoute: typeof AiAgentThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AiAgentSignupRoute: AiAgentSignupRoute,
  AiAgentThankYouRoute: AiAgentThankYouRoute,
  AiAgentIndexRoute: AiAgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
