/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAgentIndexRouteImport } from './routes/ai-agent/index'
import { Route as AiAgentSignupRouteImport } from './routes/ai-agent/signup'
import { Route as AiAgentThankYouRouteImport } from './routes/ai-agent/thank-you'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentIndexRoute = AiAgentIndexRouteImport.update({
  id: '/ai-agent/',
  path: '/ai-agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentSignupRoute = AiAgentSignupRouteImport.update({
  id: '/ai-agent/signup',
  path: '/ai-agent/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentThankYouRoute = AiAgentThankYouRouteImport.update({
  id: '/ai-agent/thank-you',
  path: '/ai-agent/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent/signup': typeof AiAgentSignupRoute
  '/ai-agent/thank-you': typeof AiAgentThankYouRoute
  '/ai-agent/': typeof AiAgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent/signup': typeof AiAgentSignupRoute
  '/ai-agent/thank-you': typeof AiAgentThankYouRoute
  '/ai-agent': typeof AiAgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent/signup': typeof AiAgentSignupRoute
  '/ai-agent/thank-you': typeof AiAgentThankYouRoute
  '/ai-agent/': typeof AiAgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-agent/signup' | '/ai-agent/thank-you' | '/ai-agent/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-agent/signup' | '/ai-agent/thank-you' | '/ai-agent'
  id:
    '__root__' | '/' | '/ai-agent/signup' | '/ai-agent/thank-you' | '/ai-agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentSignupRoute: typeof AiAgentSignupRoute
  AiAgentThankYouRoute: typeof AiAgentThankYouRoute
  AiAgentIndexRoute: typeof AiAgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent/': {
      id: '/ai-agent/'
      path: '/ai-agent'
      fullPath: '/ai-agent/'
      preLoaderRoute: typeof AiAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent/signup': {
      id: '/ai-agent/signup'
      path: '/ai-agent/signup'
      fullPath: '/ai-agent/signup'
      preLoaderRoute: typeof AiAgentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent/thank-you': {
      id: '/ai-agent/thank-you'
      path: '/ai-agent/thank-you'
      fullPath: '/ai-agent/thank-you'
      preLoaderRoute: typeof AiAgentThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentSignupRoute: AiAgentSignupRoute,
  AiAgentThankYouRoute: AiAgentThankYouRoute,
  AiAgentIndexRoute: AiAgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
